version: "3.6"
services:
  db_dani:
    image: mysql
    restart: always
    container_name: mi_base_de_datos_barna
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datata_db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer_barna
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db_dani:
        condition: service_healthy
